// Editorial content for each collection — SEO/GEO optimized articles

export interface CollectionContent {
  slug: string;
  // SEO
  metaTitle: Record<string, string>;
  metaDesc: Record<string, string>;
  h1: Record<string, string>;
  // Intro paragraph
  intro: Record<string, string>;
  // Sub-sections for the article
  sections: {
    heading: Record<string, string>;
    body: Record<string, string>;
    keywords: string[]; // search keywords for this section
    icon?: string;
  }[];
  // FAQ
  faq: { q: Record<string, string>; a: Record<string, string> }[];
  // Budget tip
  budgetTip?: Record<string, string>;
}

export const COLLECTION_CONTENT: Record<string, CollectionContent> = {
  'home-gym': {
    slug: 'home-gym',
    metaTitle: { en: 'Home Gym Essentials: Build Your Home Workout Under €50', he: 'חדר כושר ביתי: ציוד אימון ביתי בלי לשבור חסכון', fr: 'Équipement de Sport à Domicile: Salle de Sport à Moins de 50€', de: 'Heim-Fitnessstudio unter 50€: Die besten Geräte für Zuhause', es: 'Equipo de Gimnasio en Casa por menos de 50€', it: 'Palestra in Casa: Attrezzatura Sotto i 50€' },
    metaDesc: { en: 'Complete home gym setup with resistance bands, yoga mats, push-up bars & more. No membership needed, start today.', he: 'חדר כושר ביתי מלא עם רצועות התנגדות, מזרני יוגה, מתקני שכיבות סמיכה ועוד. בלי מנוי מיותר.', fr: 'Salle de sport à domicile complète avec élastiques, tapis de yoga, barres de pompes.', de: 'Komplettes Heim-Fitnessstudio mit Widerstandsbändern, Yogamatten, Liegestützgriffen.', es: 'Gimnasio en casa completo con bandas, tapetes, barras de flexiones.', it: 'Palestra in casa completa con fasce, tappetini, barre per flessioni.' },
    h1: { en: 'Build a Home Gym That Actually Works (Under €50)', he: 'בנו חדר כושר ביתי שעובד באמת (פחות מ-₪200)', fr: 'Construisez une salle de sport à domicile efficace (moins de 50€)', de: 'Baue dir ein Fitnessstudio zu Hause (unter 50€)', es: 'Construye un gimnasio en casa que funcione (menos de 50€)', it: 'Costruisci una palestra in casa che funziona (sotto i 50€)' },
    intro: { en: 'Gym memberships are expensive and time-consuming. Here\'s how to build a complete home gym with professional-grade tools — all under €50. No machines, no heavy weights, just smart equipment that delivers results.', he: 'מנוי לחדר כושר יקר וגוזל זמן. הנה איך לבנות חדר כושר ביתי שלם עם ציוד מקצועי — הכל בפחות מ-₪200.', fr: 'Les abonnements en salle coûtent cher. Voici comment construire une salle de sport chez soi pour moins de 50€.', de: 'Fitnessstudio-Mitgliedschaften sind teuer. So baust du ein Heim-Fitnessstudio für unter 50€.', es: 'Las membresías cuestan caro. Cómo construir un gimnasio en casa por menos de 50€.', it: 'Gli abbonamenti in palestra costano cari. Ecco come costruire una palestra in casa sotto i 50€.' },
    sections: [
      { heading: { en: 'Resistance Bands — Your Most Versatile Tool', he: 'רצועות התנגדות — הכלי הכי ורסטילי', fr: 'Élastiques de résistance — l\'outil le plus polyvalent', de: 'Widerstandsbänder — dein vielseitigstes Werkzeug', es: 'Bandas de resistencia — tu herramienta más versátil', it: 'Fasce di resistenza — lo strumento più versatile' },
        body: { en: 'Resistance bands aren\'t just for warm-ups. They deliver progressive resistance that actually builds muscle. Use them for squats, rows, chest presses, and pull-up assistance. A set of 3-5 bands with different resistance levels covers every major muscle group.', he: 'רצועות התנגדות זה לא רק לחימום. הן מספקות התנגדות פרוגרסיבית שבונה שריר.', fr: 'Les élastiques ne sont pas que pour l\'échauffement. Ils fournissent une résistance progressive.', de: 'Widerstandsbänder sind nicht nur zum Aufwärmen da.', es: 'Las bandas no son solo para calentar.', it: 'Le fasce elastiche non sono solo per riscaldamento.' },
        keywords: ['fitness resistance bands', 'elastic bands gym', 'workout bands set'] },
      { heading: { en: 'Yoga Mat — Your Workout Foundation', he: 'מזרן יוגה — בסיס האימון', fr: 'Tapis de yoga — la base de votre entraînement', de: 'Yogamatte — deine Trainingsbasis', es: 'Tapete de yoga — la base de tu entrenamiento', it: 'Tappetino yoga — la base del tuo allenamento' },
        body: { en: 'A good yoga mat does double duty: cushioning for floor work and grip for stability during standing exercises. Look for 6mm+ thickness and non-slip material. Use it for yoga, pilates, stretching, and bodyweight exercises.', he: 'מזרן יוגה טוב עושה עבודה כפולה: ריפוד לתרגילי רצפה ואחיזה ליציבות.', fr: 'Un bon tapis de yoga fait double emploi.', de: 'Eine gute Yogamatte hat zwei Funktionen.', es: 'Una buena esterilla hace doble función.', it: 'Un buon tappetino yoga fa doppio lavoro.' },
        keywords: ['yoga mat thick', 'exercise mat', 'pilates mat'] },
      { heading: { en: 'Push-Up Bars & Small Gear', he: 'מתקני שכיבות סמיכה וציוד קטן', fr: 'Barres de pompes et petit matériel', de: 'Liegestützgriffe & Kleingeräte', es: 'Barras de flexiones y equipo pequeño', it: 'Barre per flessioni e piccoli attrezzi' },
        body: { en: 'Push-up bars increase range of motion and reduce wrist strain. Add a jump rope for cardio, foam roller for recovery, and a pull-up bar for upper body. These small additions transform your home gym from basic to comprehensive.', he: 'מתקני שכיבות סמיכה מגדילים טווח תנועה ומפחיתים עומס על פרקי היד.', fr: 'Les barres de pompes augmentent l\'amplitude des mouvements.', de: 'Liegestützgriffe erhöhen die Bewegungsamplitude.', es: 'Las barras aumentan el rango de movimiento.', it: 'Le barre aumentano il range di movimento.' },
        keywords: ['push up bars', 'jump rope', 'foam roller', 'pull up bar door'] },
    ],
    faq: [
      { q: { en: 'Can I really build muscle with just resistance bands?', he: 'האם באפשרותי לבנות שריר רק עם רצועות התנגדות?', fr: 'Peut-on vraiment se muscler avec des élastiques ?', de: 'Kann man mit Widerstandsbändern wirklich Muskeln aufbauen?', es: '¿Se puede ganar músculo con bandas?', it: 'Si può costruire muscolo con le fasce?' },
        a: { en: 'Yes. Many professional athletes use resistance bands for strength training. The key is progressive overload — use thicker bands or increase reps as you get stronger.', he: 'כן. ספורטאים מקצועיים משתמשים ברצועות התנגדות לאימון כוח.', fr: 'Oui. De nombreux athlètes professionnels utilisent des élastiques.', de: 'Ja. Viele Profisportler nutzen Widerstandsbänder.', es: 'Sí. Muchos atletas profesionales usan bandas.', it: 'Sì. Molti atleti professionisti usano le fasce.' } },
      { q: { en: 'Do I need weights too?', he: 'האם צריך גם משקולות?', fr: 'Ai-je besoin d\'haltères aussi ?', de: 'Brauche ich auch Gewichte?', es: '¿Necesito pesas también?', it: 'Mi servono anche i pesi?' },
        a: { en: 'Not for a starter setup. Resistance bands provide enough load for most exercises, and bodyweight training is highly effective. Add weights later if you plateau.', he: 'לא בהתחלה. רצועות התנגדות מספקות עומס מספק לרוב התרגילים.', fr: 'Non pour commencer. Les élastiques suffisent.', de: 'Für den Anfang nicht. Bänder reichen aus.', es: 'No para empezar. Las bandas son suficientes.', it: 'Non per iniziare. Le fasce bastano.' } },
    ],
  },

  'coffee-ritual': {
    slug: 'coffee-ritual',
    metaTitle: { en: 'The Ultimate Home Coffee Setup: Brew Like a Pro Under €60', he: 'מערך קפה ביתי: לחלוט כמו מקצוען בפחות מ-₪250', fr: 'Kit Café à Domicile: Préparez un Café Pro à Moins de 60€', de: 'Die ultimative Kaffeestation zu Hause unter 60€', es: 'Kit de Café en Casa: Café Profesional por Menos de 60€', it: 'Kit Caffè a Casa: Caffè da Bar Sotto i 60€' },
    metaDesc: { en: 'French press, burr grinder, milk frother & more. Complete guide to brewing specialty coffee at home without the café markup.', he: 'פרנץ\' פרס, מטחנת בור, מקציף חלב ועוד. מדריך שלם לקפה מיוחד בבית.', fr: 'French press, moulin à café, mousseur à lait. Guide complet du café maison.', de: 'French Press, Kaffeemühle, Milchaufschäumer. Komplette Anleitung.', es: 'Prensa francesa, molinillo, espumador de leche.', it: 'French press, macinacaffè, montalatte.' },
    h1: { en: 'Brew Barista-Quality Coffee at Home Under €60', he: 'קפה באיכות בריסטה בבית בפחות מ-₪250', fr: 'Café de Barista à Domicile pour Moins de 60€', de: 'Barista-Qualität zu Hause unter 60€', es: 'Café de Barista en Casa por Menos de 60€', it: 'Caffè da Bar a Casa Sotto i 60€' },
    intro: { en: 'Forget the €5 café latte. With the right tools, you can make better coffee at home for a fraction of the cost. This setup pays for itself in 12 cups.', he: 'תשכחו מהקפה ב-₪20 בבית קפה. עם הכלים הנכונים, תכינו קפה טוב יותר בבית בשבריר מהעלות.', fr: 'Oubliez le café à 5€. Avec les bons outils, faites un meilleur café chez vous.', de: 'Vergiss den 5€ Café. Mit den richtigen Tools machst du besseren Kaffee zu Hause.', es: 'Olvida el café de 5€. Con las herramientas correctas.', it: 'Dimentica il caffè da 5€. Con gli strumenti giusti.' },
    sections: [
      { heading: { en: 'French Press — The Gateway to Great Coffee', he: 'פרנץ\' פרס — השער לקפה מעולה', fr: 'La French Press — l\'entrée vers un bon café', de: 'French Press — der Einstieg in großartigen Kaffee', es: 'Prensa Francesa — la puerta al buen café', it: 'French Press — l\'ingresso al buon caffè' },
        body: { en: 'A French press gives you full control over extraction. Coarse grind, 4-minute steep, plunge slowly. The result is a full-bodied, oil-rich cup that paper filters can\'t achieve. Stainless steel models keep heat better than glass.', he: 'פרנץ\' פרס נותן שליטה מלאה על המיצוי. טחינה גסה, 4 דקות חליטה, לחיצה איטית.', fr: 'La French press offre un contrôle total sur l\'extraction.', de: 'Eine French Press gibt dir volle Kontrolle über die Extraktion.', es: 'Una prensa francesa da control total sobre la extracción.', it: 'Una French press dà controllo totale sull\'estrazione.' },
        keywords: ['french press stainless steel', 'coffee plunger', 'french press 34oz'] },
      { heading: { en: 'Burr Grinder — The Secret Weapon', he: 'מטחנת בור — הנשק הסודי', fr: 'Moulin à meules — l\'arme secrète', de: 'Mahlwerk — die Geheimwaffe', es: 'Molinillo de muelas — el arma secreta', it: 'Macinino a macine — l\'arma segreta' },
        body: { en: 'A burr grinder is the single biggest upgrade you can make. Blade grinders chop unevenly; burr grinders give consistent particle size. This means even extraction and better flavor. Go for a stainless steel conical burr.', he: 'מטחנת בור היא השדרוג הכי גדול שאפשר לעשות. טחינה אחידה = מיצוי אחיד = טעם טוב יותר.', fr: 'Un moulin à meules est le meilleur investissement. Mouture homogène = extraction homogène.', de: 'Ein Mahlwerk ist das beste Upgrade. Gleichmäßiger Mahlgrad = gleichmäßige Extraktion.', es: 'Un molinillo de muelas es la mejor mejora.', it: 'Un macinino a macine è il miglior upgrade.' },
        keywords: ['coffee grinder stainless steel', 'burr coffee grinder', 'electric coffee grinder'] },
      { heading: { en: 'Milk Frother & Accessories', he: 'מקציף חלב ואביזרים', fr: 'Mousseur à lait et accessoires', de: 'Milchaufschäumer & Zubehör', es: 'Espumador de leche y accesorios', it: 'Montalatte e accessori' },
        body: { en: 'A handheld milk frother costs less than one café latte and lets you make cappuccinos, lattes, and flat whites at home. Pair with a reusable cup and coffee scale for precision.', he: 'מקציף חלב ידני עולה פחות מלאטה אחד בבית קפה ומאפשר להכין קפוצ\'ינו ולטה בבית.', fr: 'Un mousseur à lait coûte moins qu\'un latte et permet de faire cappuccinos et lattes.', de: 'Ein Milchaufschäumer kostet weniger als ein Latte.', es: 'Un espumador cuesta menos que un latte.', it: 'Un montalatte costa meno di un latte.' },
        keywords: ['milk frother handheld', 'reusable coffee cup', 'coffee scale', 'thermometer mug'] },
    ],
    faq: [
      { q: { en: 'Is a French press better than a drip machine?', he: 'האם פרנץ\' פרס עדיף על מכונת טפטוף?', fr: 'La French press est-elle meilleure qu\'une machine goutte?', de: 'Ist eine French Press besser als eine Filtermaschine?', es: '¿Es mejor la prensa que una cafetera de goteo?', it: 'La French press è meglio della moka?' },
        a: { en: 'Different results. French press gives oil-rich, full body. Drip is cleaner, lighter. French press is cheaper and easier to clean. Try both and pick your style.', he: 'תוצאות שונות. פרנץ\' פרס נותן גוף מלא ועשיר בשמנים. טפטוף נקי וקליל יותר.', fr: 'Résultats différents. La French press donne un corps riche et huileux.', de: 'Unterschiedliche Ergebnisse. French Press gibt volles Körpergefühl.', es: 'Resultados diferentes. La prensa da cuerpo completo.', it: 'Risultati diversi. French press dà corpo pieno.' } },
    ],
  },

  'content-creator': {
    slug: 'content-creator',
    metaTitle: { en: 'Content Creator Starter Kit: Record Like a Pro Under €80', he: 'ערכת קריאייטיב: להקליט כמו מקצוען בפחות מ-₪350', fr: 'Kit Créateur de Contenu: Enregistrez Comme un Pro à Moins de 80€', de: 'Content Creator Starter-Kit unter 80€', es: 'Kit Creador de Contenido: Graba Como un Pro por Menos de 80€', it: 'Kit Creator: Registra Come un Pro Sotto gli 80€' },
    metaDesc: { en: 'Complete content creation setup: lav mic, ring light, mini tripod, phone gimbal & more. Start your YouTube or TikTok channel today.', he: 'ערכת הקלטה מלאה: מיקרופון לאבליר, רינג לייט, חצובה מיני ועוד. התחילו ערוץ יוטיוב או טיקטוק.', fr: 'Kit création complet: micro-cravate, ring light, mini trépied, gimbal.', de: 'Komplettes Creator-Set: Lav-Mikrofon, Ringlicht, Mini-Stativ, Gimbal.', es: 'Kit completo: mic de solapa, ring light, mini trípode, gimbal.', it: 'Kit completo: microfono lavalier, anello luce, mini treppiede, gimbal.' },
    h1: { en: 'Start Creating Content Like a Pro (Under €80)', he: 'התחילו ליצור תוכן כמו מקצוענים (פחות מ-₪350)', fr: 'Créez du contenu comme un pro (moins de 80€)', de: 'Starte als Content Creator (unter 80€)', es: 'Crea contenido como un pro (menos de 80€)', it: 'Crea contenuti come un professionista (sotto 80€)' },
    intro: { en: 'You don\'t need a €2,000 camera to start creating content. With the right accessories, your phone can produce professional-quality video. Here\'s the kit that makes it happen.', he: 'לא צריך מצלמה ב-₪8,000 כדי להתחיל ליצור תוכן. עם האביזרים הנכונים, הטלפון שלכם יכול להפיק וידאו באיכות מקצועית.', fr: 'Pas besoin d\'un appareil à 2000€ pour créer du contenu. Avec les bons accessoires.', de: 'Du brauchst keine 2000€ Kamera. Mit dem richtigen Zubehör.', es: 'No necesitas una cámara de 2000€. Con los accesorios correctos.', it: 'Non serve una fotocamera da 2000€. Con gli accessori giusti.' },
    sections: [
      { heading: { en: 'Lavalier Microphone — Audio Is Everything', he: 'מיקרופון לאבליר — אודיו זה הכל', fr: 'Micro-cravate — l\'audio est primordial', de: 'Lavaliermikrofon — Audio ist alles', es: 'Micrófono de solapa — el audio lo es todo', it: 'Microfono a spillo — l\'audio è tutto' },
        body: { en: 'Viewers forgive imperfect video, but bad audio makes them click away instantly. A wireless lavalier mic clips to your collar and connects directly to your phone. Crystal clear voice, no background noise.', he: 'צופים סולחים על וידאו לא מושלם, אבל אודיו גרוע גורם להם לעזוב מיד.', fr: 'Les spectateurs pardonnent une vidéo imparfaite, mais un mauvais audio les fait fuir.', de: 'Zuschauer verzeihen schlechtes Video, aber schlechter Ton vertreibt sie sofort.', es: 'Los espectadores perdonan el video imperfecto.', it: 'Gli spettatori perdonano il video imperfetto.' },
        keywords: ['wireless lavalier microphone', 'phone microphone', 'lapel mic iPhone'] },
      { heading: { en: 'Ring Light & Mini Tripod', he: 'רינג לייט וחצובה מיני', fr: 'Ring light et mini trépied', de: 'Ringlicht & Mini-Stativ', es: 'Ring light y mini trípode', it: 'Anello luce e mini treppiede' },
        body: { en: 'Good lighting separates amateur from pro. A ring light with adjustable color temperature gives you studio-quality light anywhere. Pair with a mini tripod that doubles as a selfie stick and phone mount.', he: 'תאורה טובה מבדילה בין חובבן למקצוען. רינג לייט עם טמפרטורת צבע מתכווננת נותן אור באיכות סטודיו.', fr: 'Un bon éclairage sépare l\'amateur du pro. Un ring light avec température ajustable.', de: 'Gutes Licht trennt Amateur von Profi. Ein Ringlicht mit einstellbarer Farbtemperatur.', es: 'La buena iluminación separa al amateur del profesional.', it: 'La buona illuminazione separa l\'amatore dal professionista.' },
        keywords: ['ring light with tripod', 'phone tripod selfie', 'LED ring light 10'] },
      { heading: { en: 'Phone Gimbal for Smooth Video', he: 'גימבל לטלפון — וידאו חלק', fr: 'Gimbal pour smartphone — vidéo fluide', de: 'Handy-Gimbal — flüssige Videos', es: 'Gimbal para móvil — video suave', it: 'Gimbal per smartphone — video fluido' },
        body: { en: 'Nothing screams amateur like shaky footage. A 3-axis phone gimbal stabilizes your video while you walk, run, or pan. Modern gimbals also include tracking modes that follow your face automatically.', he: 'שום דבר לא צורח "חובבן" כמו צילום רועד. גימבל 3 צירים מייצב את הוידאו.', fr: 'Rien ne crie amateur comme des images tremblantes. Un gimbal 3 axes stabilise.', de: 'Nichts schreit Amateur wie verwackelte Aufnahmen. Ein 3-Achsen-Gimbal stabilisiert.', es: 'Nada grita amateur como imágenes temblorosas.', it: 'Niente urla amatore come le riprese traballanti.' },
        keywords: ['phone gimbal stabilizer', 'smartphone gimbal', 'handheld gimbal iPhone'] },
    ],
    faq: [
      { q: { en: 'Is phone video good enough for YouTube?', he: 'האם וידאו מטלפון מספיק טוב ליוטיוב?', fr: 'La vidéo de smartphone est-elle assez bonne pour YouTube ?', de: 'Ist Handy-Video gut genug für YouTube?', es: '¿Es el video de móvil suficiente para YouTube?', it: 'Il video dello smartphone è abbastanza per YouTube?' },
        a: { en: 'Absolutely. Many top YouTubers shoot entirely on iPhones. Good audio and lighting matter more than camera quality.', he: 'בהחלט. יוטיוברים מובילים מצלמים כולו באייפון. אודיו ותאורה טובים חשובים יותר מאיכות מצלמה.', fr: 'Absolument. De nombreux YouTubeurs tournent entièrement sur iPhone.', de: 'Absolut. Viele Top-YouTuber drehen komplett auf dem iPhone.', es: 'Absolutamente. Muchos YouTubers graban con iPhone.', it: 'Assolutamente. Molti YouTuber girano solo con iPhone.' } },
    ],
  },

  'balcony-garden': {
    slug: 'balcony-garden',
    metaTitle: { en: 'Balcony Garden Starter Kit: Grow Herbs & Veggies in Small Spaces', he: 'גינת מרפסת: לגדל עשבי תיבול וירקות במרחב קטן', fr: 'Kit Jardin de Balcon: Faites Pousser Herbes et Légumes en Petit Espace', de: 'Balkon-Garten: Kräuter & Gemüse auf kleinem Raum anbauen', es: 'Kit Jardín de Balcón: Cultiva Hierbas y Verduras en Espacios Pequeños', it: 'Kit Giardino da Balcone: Coltiva Erbe e Verdure in Piccoli Spazi' },
    metaDesc: { en: 'Grow your own herbs, veggies and flowers on a balcony. Smart pots, irrigation systems, grow lights & seed starters — complete setup under €40.', he: 'לגדל עשבי תיבול, ירקות ופרחים במרפסת. עציצים חכמים, מערכות השקיה ואורות גידול — פחות מ-₪160.', fr: 'Faites pousser herbes, légumes et fleurs sur votre balcon. Moins de 40€.', de: 'Kräuter, Gemüse und Blumen auf dem Balkon anbauen. Komplett unter 40€.', es: 'Cultiva hierbas, verduras y flores en tu balcón. Completo por menos de 40€.', it: 'Coltiva erbe, verdure e fiori sul balcone. Completo sotto i 40€.' },
    h1: { en: 'Turn Your Balcony Into a Productive Garden (Under €40)', he: 'הפכו את המרפסת לגינה פורייה (פחות מ-₪160)', fr: 'Transformez votre balcon en jardin productif (moins de 40€)', de: 'Mach deinen Balkon zum Nutzgarten (unter 40€)', es: 'Convierte tu balcón en un jardín productivo (menos de 40€)', it: 'Trasforma il tuo balcone in un giardino produttivo (sotto 40€)' },
    intro: { en: 'Fresh herbs and cherry tomatoes at arm\'s reach. A balcony garden is not only satisfying and beautiful — it saves money on groceries. Here\'s everything you need to start growing, no green thumb required.', he: 'עשבי תיבול טריים ועגבניות שרי בהישג יד. גינת מרפסת לא רק מספקת ויפה — היא חוסכת כסף על קניות.', fr: 'Herbes fraîches et tomates cerises à portée de main. Un jardin de balcon économique.', de: 'Frische Kräuter und Cherrytomaten in Reichweite. Ein Balkongarten spart Geld.', es: 'Hierbas frescas y tomates cherry al alcance de la mano.', it: 'Erbe fresche e pomodorini a portata di mano.' },
    sections: [
      { heading: { en: 'Vertical Planters & Grow Bags', he: 'עציצים אנכיים ושקיות גידול', fr: 'Pots verticaux et sacs de culture', de: 'Vertikale Pflanzgefäße & Grow Bags', es: 'Macetas verticales y bolsas de cultivo', it: 'Vasi verticali e sacchi per coltivazione' },
        body: { en: 'Don\'t have floor space? Grow up. Vertical planters with multiple pockets let you grow 10+ plants in the footprint of one pot. Fabric grow bags promote healthy root growth and prevent overwatering. Perfect for tomatoes, peppers, and herbs.', he: 'אין מקום על הרצפה? גדלו למעלה. עציצים אנכיים עם כיסים מרובים מאפשרים לגדל 10+ צמחים.', fr: 'Pas de place au sol ? Cultivez en hauteur. Pots verticaux à poches multiples.', de: 'Kein Bodenplatz? Wachst nach oben. Vertikale Pflanzgefäße mit mehreren Taschen.', es: '¿Sin espacio en el suelo? Cultiva hacia arriba.', it: 'Niente spazio a terra? Coltiva in verticale.' },
        keywords: ['vertical garden planter', 'grow bag fabric', 'wall hanging planter'] },
      { heading: { en: 'Smart Irrigation — Water Less, Grow More', he: 'השקיה חכמה — להשקות פחות, לגדל יותר', fr: 'Irrigation intelligente — arrosez moins, cultivez plus', de: 'Intelligente Bewässerung', es: 'Riego inteligente', it: 'Irrigazione intelligente' },
        body: { en: 'Forget daily watering. A solar-powered drip irrigation system waters your plants automatically. It uses solar energy, has adjustable flow, and can run for days without refilling. Perfect for busy people who want a garden without the chore.', he: 'תשכחו מהשקיה יומית. מערכת טפטוף סולארית משקה אוטומטית. אידיאלית לאנשים עסוקים שרוצים גינה.', fr: 'Oubliez l\'arrosage quotidien. Un système d\'irrigation goutte à goutte solaire automatique.', de: 'Vergiss das tägliche Gießen. Ein solarbetriebenes Tropfbewässerungssystem.', es: 'Olvida el riego diario. Un sistema de riego por goteo solar.', it: 'Dimentica l\'irrigazione quotidiana.' },
        keywords: ['solar drip irrigation', 'automatic watering system', 'self watering plant pot'] },
    ],
    faq: [
      { q: { en: 'Can I grow vegetables on a shady balcony?', he: 'האם אפשר לגדל ירקות במרפסת מוצלת?', fr: 'Peut-on cultiver des légumes sur un balcon ombragé ?', de: 'Kann man auf einem schattigen Balkon Gemüse anbauen?', es: '¿Se pueden cultivar verduras en un balcón sombreado?', it: 'Si possono coltivare verdure su un balcone ombreggiato?' },
        a: { en: 'Yes. Leafy greens (lettuce, spinach, kale) and herbs (mint, parsley, cilantro) actually prefer partial shade. For sun-lovers (tomatoes, peppers), use a clip-on grow light.', he: 'כן. עלים ירוקים ועשבי תיבול מעדיפים צל חלקי. לחובבי שמש, השתמשו באור גידול.', fr: 'Oui. Les salades et herbes aromatiques préfèrent l\'ombre partielle.', de: 'Ja. Blattgemüse und Kräuter bevorzugen Halbschatten.', es: 'Sí. Las lechugas y hierbas prefieren sombra parcial.', it: 'Sì. Le insalate e le erbe preferiscono l\'ombra parziale.' } },
    ],
  },

  'sleep-sanctuary': {
    slug: 'sleep-sanctuary',
    metaTitle: { en: 'Create a Sleep Sanctuary: The Ultimate Bedtime Setup Under €40', he: 'פינת שינה מושלמת: ערכת שינה משפרת איכות בפחות מ-₪150', fr: 'Créez un Sanctuaire du Sommeil: Le Kit Ultimate Moins de 40€', de: 'Schlaf-Oase: Das ultimative Schlafzimmer-Set unter 40€', es: 'Crea un Santuario del Sueño: El Kit Definitivo por menos de 40€', it: 'Crea un Santuario del Sonno: Il Kit Definitivo Sotto i 40€' },
    metaDesc: { en: 'Natural sleep aids: weighted eye mask, lavender pillow, aromatherapy diffuser, memory foam pillow. Better sleep starts tonight.', he: 'עזרי שינה טבעיים: מסכת עיניים, כרית לבנדר, מפזר ארומתרפיה, כרית זיכרון. שינה טובה יותר מתחילה הלילה.', fr: 'Aides naturelles au sommeil: masque, coussin lavande, diffuseur, oreiller mémoire de forme.', de: 'Natürliche Schlafhilfen: Maske, Lavendelkissen, Diffuser, Memory-Foam-Kissen.', es: 'Ayudas naturales: máscara, almohada de lavanda, difusor, almohada de espuma.', it: 'Aiuti naturali: mascherina, cuscino lavanda, diffusore, cuscino memory foam.' },
    h1: { en: 'Transform Your Bedroom Into a Sleep Sanctuary (Under €40)', he: 'הפכו את חדר השינה לפינת שינה מושלמת (פחות מ-₪150)', fr: 'Transformez votre chambre en sanctuaire du sommeil (moins de 40€)', de: 'Verwandle dein Schlafzimmer in eine Wohlfühloase (unter 40€)', es: 'Transforma tu dormitorio en un santuario del sueño (menos de 40€)', it: 'Trasforma la tua camera da letto in un santuario (sotto 40€)' },
    intro: { en: 'Sleep is the foundation of health, yet most of us don\'t treat it that way. Ditch the sleeping pills and create a natural sleep environment that helps you fall asleep faster and wake up refreshed. Here\'s how for under €40.', he: 'שינה היא בסיס הבריאות, אבל רובנו לא מתייחסים לזה ככה. צרו סביבת שינה טבעית שעוזרת להירדם מהר יותר.', fr: 'Le sommeil est la base de la santé. Créez un environnement naturel pour mieux dormir.', de: 'Schlaf ist die Grundlage der Gesundheit. Schaffe eine natürliche Schlafumgebung.', es: 'El sueño es la base de la salud. Crea un ambiente natural.', it: 'Il sonno è la base della salute. Crea un ambiente naturale.' },
    sections: [
      { heading: { en: 'Weighted Eye Mask & Lavender Pillow', he: 'מסכת עיניים משוקללת וכרית לבנדר', fr: 'Masque lesté et coussin à la lavande', de: 'Gewichts-Augenmaske & Lavendelkissen', es: 'Máscara ponderada y almohada de lavanda', it: 'Mascherina pesata e cuscino alla lavanda' },
        body: { en: 'A weighted silk eye mask blocks 100% of light while gentle pressure signals your nervous system to relax. Pair with a microwavable lavender pillow — the warmth and aromatherapy work together to lower cortisol before sleep.', he: 'מסכת משי משוקללת חוסמת 100% אור כשהלחץ העדין מאותת למערכת העצבים להירגע.', fr: 'Un masque en soie lesté bloque 100% de la lumière. Associez à un coussin lavande.', de: 'Eine gewichtete Seidenmaske blockiert 100% des Lichts. Kombiniere mit Lavendelkissen.', es: 'Una máscara de seda ponderada bloquea el 100% de la luz.', it: 'Una mascherina di seta pesata blocca il 100% della luce.' },
        keywords: ['silk sleep mask', 'weighted eye pillow', 'lavender eye pillow microwavable', 'aromatherapy sleep mask'] },
      { heading: { en: 'Aromatherapy Diffuser for Deep Sleep', he: 'מפזר ארומתרפיה לשינה עמוקה', fr: 'Diffuseur d\'aromathérapie pour un sommeil profond', de: 'Aromatherapie-Diffuser für tiefen Schlaf', es: 'Difusor de aromaterapia para sueño profundo', it: 'Diffusore di aromaterapia per sonno profondo' },
        body: { en: 'An ultrasonic aromatherapy diffuser turns essential oils into a fine, cool mist. Add 3-5 drops of lavender or chamomile oil 30 minutes before bed. The diffuser also adds humidity — helpful for dry bedrooms in winter or AC rooms in summer.', he: 'מפזר אולטרה-סוני הופך שמנים אתריים לערפל דק וקריר. מוסיפים 3-5 טיפות לבנדר או קמומיל.', fr: 'Un diffuseur ultrasonique transforme les huiles essentielles en fine brume.', de: 'Ein Ultraschall-Diffuser verwandelt ätherische Öle in feinen Nebel.', es: 'Un difusor ultrasónico convierte aceites esenciales en niebla.', it: 'Un diffusore a ultrasuoni trasforma gli oli essenziali in nebbia.' },
        keywords: ['aromatherapy diffuser ultrasonic', 'essential oil diffuser', 'cool mist humidifier'] },
      { heading: { en: 'Memory Foam Pillow & White Noise', he: 'כרית זיכרון ורעש לבן', fr: 'Oreiller mémoire de forme et bruit blanc', de: 'Memory-Foam-Kissen & weißes Rauschen', es: 'Almohada viscoelástica y ruido blanco', it: 'Cuscino memory foam e rumore bianco' },
        body: { en: 'A contoured memory foam pillow keeps your spine aligned while you sleep. Combine with a white noise machine or app to mask street noise. Your brain stops reacting to sudden sounds, leading to deeper, uninterrupted sleep cycles.', he: 'כרית זיכרון מעוצבת שומרת על יישור עמוד השדרה. בשילוב עם רעש לבן המוח מפסיק להגיב לצלילים פתאומיים.', fr: 'Un oreiller en mousse à mémoire de forme maintient l\'alignement de la colonne.', de: 'Ein konturiertes Memory-Schaum-Kissen hält die Wirbelsäule gerade.', es: 'Una almohada viscoelástica mantiene la columna alineada.', it: 'Un cuscino in memory foam mantiene la colonna allineata.' },
        keywords: ['memory foam contour pillow', 'orthopedic pillow neck pain', 'white noise machine'] },
    ],
    faq: [
      { q: { en: 'Does aromatherapy actually help with sleep?', he: 'האם ארומתרפיה באמת עוזרת לשינה?', fr: 'L\'aromathérapie aide-t-elle vraiment à dormir ?', de: 'Hilft Aromatherapie wirklich beim Schlafen?', es: '¿Ayuda la aromaterapia a dormir?', it: 'L\'aromaterapia aiuta davvero a dormire?' },
        a: { en: 'Studies show lavender and chamomile reduce cortisol levels and heart rate, promoting the relaxation response needed for sleep onset. It\'s not a cure for insomnia, but it creates the right conditions for natural sleep.', he: 'מחקרים מראים שלבנדר וקמומיל מורידים רמות קורטיזול ודופק, ומקדמים הרפיה.', fr: 'Des études montrent que la lavande réduit le cortisol et favorise la relaxation.', de: 'Studien zeigen, dass Lavendel und Kamille den Cortisolspiegel senken.', es: 'Estudios muestran que la lavanda reduce el cortisol.', it: 'Studi mostrano che lavanda e camomilla riducono il cortisolo.' } },
    ],
  },
};